(function(){
'use strict';
var canvas=document.getElementById('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
var W=360,H=640,MAX_Z=110,running=false,lastTime=0,distance=0,coins=0,worldSpeed=22,wave=1,shootTimer=0,spawnTimer=0,gateTimer=7,bossTimer=24,chestTimer=14,dragging=false,screenShake=0,whiteFlash=0,combo=0,maxCombo=0,comboTimer=0,bossBanner=0,waveBanner=0,gameTime=0,muted=false;
var bullets=[],enemies=[],gates=[],chests=[],particles=[],floatTexts=[],roadTiles=[],clouds=[],petals=[];
var player={x:0,targetX:0,hp:3,maxHp:5,damage:1,fireRate:5,bulletCount:1,shield:0,magnet:0,invincible:0};
function id(n){return document.getElementById(n)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function lerp(a,b,t){return a+(b-a)*t}function rand(a,b){return a+Math.random()*(b-a)}function ir(v){return Math.round(v)}
var audioCtx=null;
function tone(freq,duration,type,volume){if(muted)return;try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();var osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type||'square';osc.frequency.value=freq;gain.gain.setValueAtTime(volume||.035,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration)}catch(e){}}
function sfx(name){if(name==='shoot')tone(520,.035,'square',.015);if(name==='hit')tone(180,.05,'square',.025);if(name==='pop'){tone(330,.07,'square',.035);setTimeout(function(){tone(520,.08,'square',.025)},35)}if(name==='hurt')tone(90,.22,'sawtooth',.05);if(name==='upgrade'){tone(440,.08,'square',.035);setTimeout(function(){tone(660,.1,'square',.03)},70)}if(name==='boss')tone(75,.45,'sawtooth',.05);if(name==='chest'){tone(660,.07,'square',.03);setTimeout(function(){tone(880,.12,'square',.03)},60)}}
function resetWorldDecor(){roadTiles=[];clouds=[];petals=[];var i;for(i=0;i<26;i++)roadTiles.push({z:i*(MAX_Z/26),lane:i%3-1});for(i=0;i<7;i++)clouds.push({x:Math.floor(Math.random()*W),y:40+Math.floor(Math.random()*100),s:Math.floor(rand(1,3)),speed:rand(2,6)});for(i=0;i<28;i++)petals.push({x:rand(0,W),y:rand(120,H),vx:rand(-8,8),vy:rand(10,26),size:Math.floor(rand(2,5))})}
function project(x,z){var depth=clamp(1-z/MAX_Z,0,1),curve=Math.pow(depth,1.45),roadHalf=lerp(30,190,curve);return{x:W/2+x*roadHalf,y:lerp(145,525,curve),s:lerp(.18,1.08,curve),depth:depth,roadHalf:roadHalf}}
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(ir(x),ir(y),Math.max(1,ir(w)),Math.max(1,ir(h)))}
function outlineRect(x,y,w,h,fill,outline,thick){thick=thick||3;rect(x-thick,y-thick,w+thick*2,h+thick*2,outline);rect(x,y,w,h,fill)}
function pixelText(text,x,y,size,color,align){ctx.save();ctx.font='900 '+size+'px "Courier New","Noto Sans TC",monospace';ctx.textAlign=align||'center';ctx.textBaseline='middle';ctx.fillStyle='#35243c';ctx.fillText(text,ir(x+2),ir(y+2));ctx.fillStyle=color||'#fff8dc';ctx.fillText(text,ir(x),ir(y));ctx.restore()}
function updateHud(){id('coins').textContent=coins;id('distance').textContent=Math.floor(distance);id('wave').textContent='第 '+wave+' 波';id('stats').textContent='豆餡彈 '+player.damage+'｜連發 '+player.fireRate.toFixed(1)+'｜分身 '+player.bulletCount+'｜愛心 '+player.hp+(player.shield>0?'｜護盾':'')+(player.magnet>0?'｜磁力':'')}
function resetGame(){distance=0;coins=0;worldSpeed=22;wave=1;shootTimer=0;spawnTimer=.7;gateTimer=6.5;bossTimer=22;chestTimer=12;screenShake=0;whiteFlash=0;combo=0;maxCombo=0;comboTimer=0;bossBanner=0;waveBanner=1.4;gameTime=0;bullets=[];enemies=[];gates=[];chests=[];particles=[];floatTexts=[];player.x=0;player.targetX=0;player.hp=3;player.damage=1;player.fireRate=5;player.bulletCount=1;player.shield=0;player.magnet=0;player.invincible=0;resetWorldDecor();updateHud()}
function startGame(){resetGame();running=true;lastTime=performance.now();id('startScreen').classList.add('hide');id('gameOverScreen').classList.add('hide');if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume();requestAnimationFrame(loop)}
function endGame(title){running=false;id('resultTitle').textContent=title||'大福扁掉了';id('finalDistance').textContent=Math.floor(distance);id('finalCoins').textContent=coins;id('finalCombo').textContent=maxCombo;id('gameOverScreen').classList.remove('hide')}
function addText(text,x,y,color,size){floatTexts.push({text:text,x:x,y:y,color:color||'#fff8dc',size:size||18,life:.8})}
function burst(x,y,color,count,power){count=count||16;power=power||100;for(var i=0;i<count;i++){var a=Math.random()*Math.PI*2,v=rand(20,power);particles.push({x:x,y:y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,size:Math.floor(rand(2,6)),life:rand(.25,.7),color:color})}}
function spawnEnemy(boss){if(boss){var bossHp=Math.floor(65+distance*.2+wave*10);enemies.push({x:0,z:MAX_Z+4,hp:bossHp,maxHp:bossHp,size:1.55,type:'boss',reward:28+wave*2,wobble:0});bossBanner=2;sfx('boss');return}var lanes=[-.66,0,.66],count=Math.random()<Math.min(.28+wave*.025,.5)?2:1,used={},types=['anko','matcha','strawberry','sesame'];for(var i=0;i<count;i++){var lane;do{lane=lanes[Math.floor(Math.random()*lanes.length)]}while(used[lane]);used[lane]=true;var hp=Math.max(3,Math.floor(5+distance*.038+wave*1.4+Math.random()*8));enemies.push({x:lane,z:MAX_Z+i*4,hp:hp,maxHp:hp,size:rand(.72,.9),type:types[Math.floor(Math.random()*types.length)],reward:Math.ceil(hp/4),wobble:Math.random()*6.28})}}
function spawnGate(){var pairs=[[['+1 分身','bullet',1,'#6cd4ff'],['+1 豆餡','damage',1,'#ffbc5c']],[['+35% 連發','rate',.35,'#73d6a4'],['+1 愛心','hp',1,'#ff8fa8']],[['+2 豆餡','damage',2,'#ff9f50'],['護盾','shield',1,'#c39bff']],[['豆磁鐵','magnet',7,'#70c9ef'],['+50% 連發','rate',.5,'#73d6a4']]],pair=pairs[Math.floor(Math.random()*pairs.length)];gates.push({z:MAX_Z,left:pair[0],right:pair[1],used:false})}
function spawnChest(){var lanes=[-.62,0,.62],x=lanes[Math.floor(Math.random()*3)];chests.push({x:x,z:MAX_Z,hp:6+wave*2,maxHp:6+wave*2,opened:false})}
function shoot(){for(var i=0;i<player.bulletCount;i++)bullets.push({x:player.x+(i-(player.bulletCount-1)/2)*.16,z:3,speed:72,alive:true,damage:player.damage});sfx('shoot')}
function applyUpgrade(o){if(o[1]==='bullet')player.bulletCount=Math.min(5,player.bulletCount+o[2]);if(o[1]==='damage')player.damage+=o[2];if(o[1]==='rate')player.fireRate=Math.min(13,player.fireRate*(1+o[2]));if(o[1]==='hp')player.hp=Math.min(player.maxHp,player.hp+o[2]);if(o[1]==='shield')player.shield=1;if(o[1]==='magnet')player.magnet=Math.max(player.magnet,o[2]);whiteFlash=.18;screenShake=4;addText(o[0],W/2,285,o[3],24);burst(W/2,330,o[3],30,150);sfx('upgrade');updateHud()}
function openChest(chest){if(chest.opened)return;chest.opened=true;var rewards=[['+3 紅豆','coins',3],['+1 豆餡','damage',1],['+20% 連發','rate',.2],['回復愛心','hp',1],['護盾','shield',1]],r=rewards[Math.floor(Math.random()*rewards.length)];if(r[1]==='coins')coins+=r[2];if(r[1]==='damage')player.damage+=r[2];if(r[1]==='rate')player.fireRate=Math.min(13,player.fireRate*(1+r[2]));if(r[1]==='hp')player.hp=Math.min(player.maxHp,player.hp+r[2]);if(r[1]==='shield')player.shield=1;var p=project(chest.x,chest.z);addText(r[0],p.x,p.y-35,'#ffd56a',20);burst(p.x,p.y,'#ffd56a',34,170);sfx('chest');updateHud()}
function damagePlayer(){if(player.invincible>0)return;if(player.shield>0){player.shield=0;player.invincible=.7;addText('護盾破裂!',project(player.x,0).x,445,'#c39bff',20);burst(project(player.x,0).x,505,'#c39bff',28,160)}else{player.hp--;player.invincible=1.1;addText('-1 愛心',project(player.x,0).x,445,'#ff718f',20);burst(project(player.x,0).x,505,'#ff718f',26,150);if(player.hp<=0){updateHud();sfx('hurt');endGame('大福扁掉了');return}}combo=0;screenShake=12;whiteFlash=.25;sfx('hurt');updateHud()}
function update(dt){
gameTime+=dt;distance+=worldSpeed*dt*.72;worldSpeed=Math.min(37,22+distance*.012+wave*.35);var newWave=1+Math.floor(distance/180);if(newWave!==wave){wave=newWave;waveBanner=1.6;spawnTimer=.25;updateHud()}player.invincible=Math.max(0,player.invincible-dt);player.magnet=Math.max(0,player.magnet-dt);player.x+=(player.targetX-player.x)*Math.min(1,dt*13);player.x=clamp(player.x,-.88,.88);comboTimer-=dt;if(comboTimer<=0)combo=0;bossBanner=Math.max(0,bossBanner-dt);waveBanner=Math.max(0,waveBanner-dt);
shootTimer-=dt;if(shootTimer<=0){shoot();shootTimer=1/player.fireRate}spawnTimer-=dt;if(spawnTimer<=0){spawnEnemy(false);spawnTimer=Math.max(.6,1.62-distance*.0012-wave*.035)*rand(.82,1.2)}gateTimer-=dt;if(gateTimer<=0){spawnGate();gateTimer=10+Math.random()*5}bossTimer-=dt;if(bossTimer<=0){spawnEnemy(true);bossTimer=Math.max(23,31-wave*.7)+Math.random()*7}chestTimer-=dt;if(chestTimer<=0){spawnChest();chestTimer=14+Math.random()*9}
var i,j;for(i=0;i<roadTiles.length;i++){roadTiles[i].z-=worldSpeed*dt;if(roadTiles[i].z<0)roadTiles[i].z+=MAX_Z}for(i=0;i<clouds.length;i++){clouds[i].x+=clouds[i].speed*dt;if(clouds[i].x>W+40)clouds[i].x=-60}for(i=0;i<petals.length;i++){petals[i].x+=petals[i].vx*dt;petals[i].y+=petals[i].vy*dt;if(petals[i].y>H){petals[i].y=120;petals[i].x=rand(0,W)}if(petals[i].x<0)petals[i].x=W;if(petals[i].x>W)petals[i].x=0}for(i=0;i<bullets.length;i++){bullets[i].z+=bullets[i].speed*dt;if(bullets[i].z>MAX_Z+14)bullets[i].alive=false}for(i=0;i<enemies.length;i++){enemies[i].z-=worldSpeed*dt;enemies[i].wobble+=dt*2.5}for(i=0;i<gates.length;i++)gates[i].z-=worldSpeed*dt;for(i=0;i<chests.length;i++)chests[i].z-=worldSpeed*dt;
for(i=0;i<bullets.length;i++){var b=bullets[i];if(!b.alive)continue;var hitSomething=false;for(j=0;j<enemies.length;j++){var e=enemies[j],hitWidth=e.type==='boss'?.57:.34*e.size;if(Math.abs(b.z-e.z)<3.6&&Math.abs(b.x-e.x)<hitWidth){b.alive=false;e.hp-=b.damage;var hit=project(e.x,e.z);burst(hit.x,hit.y-12,'#ffca4f',5,65);addText('-'+b.damage,hit.x,hit.y-24,'#fff8dc',14);sfx('hit');hitSomething=true;break}}if(hitSomething)continue;for(j=0;j<chests.length;j++){var c=chests[j];if(!c.opened&&Math.abs(b.z-c.z)<3.6&&Math.abs(b.x-c.x)<.34){b.alive=false;c.hp-=b.damage;if(c.hp<=0)openChest(c);sfx('hit');break}}}
for(i=enemies.length-1;i>=0;i--){var enemy=enemies[i];if(enemy.hp<=0){var ep=project(enemy.x,enemy.z);combo++;maxCombo=Math.max(maxCombo,combo);comboTimer=2.2;var reward=enemy.reward+Math.floor(combo/5);coins+=reward;addText('+'+reward+(combo>=5?' 連擊!':''),ep.x,ep.y-28,'#ffd56a',enemy.type==='boss'?26:18);burst(ep.x,ep.y,enemy.type==='boss'?'#8bcf75':'#ff8fa8',enemy.type==='boss'?52:24,enemy.type==='boss'?230:130);screenShake=enemy.type==='boss'?12:4;sfx('pop');enemies.splice(i,1);updateHud();continue}if(enemy.z<=1.5){var width=enemy.type==='boss'?.62:.39*enemy.size;if(Math.abs(enemy.x-player.x)<width)damagePlayer();enemies.splice(i,1)}}
for(i=chests.length-1;i>=0;i--){var chest=chests[i];if(chest.opened){chests.splice(i,1);continue}if(chest.z<=1.5){if(Math.abs(chest.x-player.x)<.38)openChest(chest);chests.splice(i,1)}}for(i=gates.length-1;i>=0;i--){var g=gates[i];if(g.z<=2&&!g.used){g.used=true;applyUpgrade(player.x<0?g.left:g.right)}if(g.z<-5)gates.splice(i,1)}
bullets=bullets.filter(function(v){return v.alive});for(i=particles.length-1;i>=0;i--){var q=particles[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.96;q.vy*=.96;q.life-=dt;if(q.life<=0)particles.splice(i,1)}for(i=floatTexts.length-1;i>=0;i--){floatTexts[i].y-=38*dt;floatTexts[i].life-=dt;if(floatTexts[i].life<=0)floatTexts.splice(i,1)}screenShake*=.82;whiteFlash=Math.max(0,whiteFlash-dt)}
function drawSky(){var sky=wave%3;rect(0,0,W,H,sky===0?'#8bc4ef':sky===1?'#79cfe9':'#9eb8ef');rect(0,138,W,H-138,sky===2?'#8bc978':'#8ed276');rect(286,54,34,34,'#ffe785');rect(292,48,22,46,'#ffe785');rect(280,60,46,22,'#ffe785');var i;for(i=0;i<clouds.length;i++){var c=clouds[i],s=c.s*4;rect(c.x,c.y+s,s*7,s*2,'#eafaff');rect(c.x+s,c.y,s*4,s*4,'#eafaff');rect(c.x+s*4,c.y+s,s*3,s*3,'#eafaff')}rect(0,118,W,28,'#68b96d');for(i=0;i<12;i++){var mx=i*34-18,my=118-(i%3)*10;rect(mx,my,42,28,'#5aa35f');rect(mx+8,my-10,24,16,'#5aa35f')}}
function drawRoad(){ctx.fillStyle='#c38f68';ctx.beginPath();ctx.moveTo(148,145);ctx.lineTo(348,640);ctx.lineTo(12,640);ctx.lineTo(212,145);ctx.closePath();ctx.fill();ctx.fillStyle='#f1c994';ctx.beginPath();ctx.moveTo(155,145);ctx.lineTo(326,640);ctx.lineTo(34,640);ctx.lineTo(205,145);ctx.closePath();ctx.fill();for(var i=0;i<roadTiles.length;i++){var t=roadTiles[i],p=project(t.lane*.47,t.z),s=Math.max(2,12*p.s),checker=(Math.floor((t.z+distance)/7)+t.lane)%2===0?'#fff0c6':'#e9b97e';rect(p.x-s/2,p.y-s/2,s,s,checker)}rect(8,548,26,92,'#71bd68');rect(326,548,26,92,'#71bd68');for(i=0;i<8;i++){rect(8+i%2*8,556+i*11,8,8,'#e6f3a1');rect(340-i%2*8,556+i*11,8,8,'#e6f3a1')}}
function drawPetals(){for(var i=0;i<petals.length;i++)rect(petals[i].x,petals[i].y,petals[i].size,petals[i].size,'#ffd1df')}
function drawDaifuku(x,y,s){s=Math.max(.35,s);var u=Math.max(1,Math.round(4*s));ctx.save();ctx.translate(ir(x),ir(y));rect(-8*u,5*u,16*u,3*u,'#0005');rect(-7*u,-3*u,14*u,9*u,'#35243c');rect(-6*u,-4*u,12*u,9*u,'#fff8dc');rect(-5*u,-5*u,10*u,2*u,'#fff8dc');rect(-6*u,-1*u,12*u,3*u,'#fffdf3');rect(-4*u,-5*u,8*u,1*u,'#ff6f7f');rect(-5*u,-6*u,2*u,2*u,'#ff6f7f');rect(3*u,-6*u,2*u,2*u,'#ff6f7f');rect(-3*u,-1*u,1*u,2*u,'#35243c');rect(2*u,-1*u,1*u,2*u,'#35243c');rect(-1*u,1*u,2*u,1*u,'#8e4d5a');rect(-5*u,1*u,2*u,1*u,'#ff9caf');rect(3*u,1*u,2*u,1*u,'#ff9caf');rect(-2*u,-8*u,4*u,4*u,'#35243c');rect(-1*u,-10*u,2*u,3*u,'#ffca4f');ctx.restore()}
function drawEnemy(e){var p=project(e.x+Math.sin(e.wobble)*.01,e.z);if(!p.depth)return;if(e.type==='boss'){drawBoss(p.x,p.y-20*p.s,e.size*p.s);return}var u=Math.max(1,Math.round(4*e.size*p.s)),body=e.type==='matcha'?'#a8d37d':e.type==='strawberry'?'#ff9eb4':e.type==='sesame'?'#777084':'#d88a66';ctx.save();ctx.translate(ir(p.x),ir(p.y-8*p.s));rect(-7*u,-5*u,14*u,11*u,'#35243c');rect(-6*u,-6*u,12*u,11*u,body);rect(-4*u,-7*u,8*u,2*u,body);rect(-4*u,-2*u,2*u,1*u,'#35243c');rect(2*u,-2*u,2*u,1*u,'#35243c');rect(-3*u,1*u,6*u,1*u,'#35243c');rect(-1*u,2*u,2*u,1*u,'#35243c');ctx.restore();pixelText(String(Math.max(0,Math.ceil(e.hp))),p.x,p.y-44*p.s,Math.max(10,Math.round(20*p.s)),'#fff8dc')}
function drawBoss(x,y,s){var u=Math.max(1,Math.round(5*s));ctx.save();ctx.translate(ir(x),ir(y));rect(-9*u,-7*u,18*u,14*u,'#35243c');rect(-8*u,-8*u,16*u,14*u,'#a8d37d');rect(-6*u,-9*u,12*u,2*u,'#a8d37d');rect(-5*u,-2*u,2*u,2*u,'#35243c');rect(3*u,-2*u,2*u,2*u,'#35243c');rect(-3*u,2*u,6*u,2*u,'#35243c');rect(-8*u,-11*u,16*u,2*u,'#ff6f7f');rect(-8*u,-13*u,3*u,3*u,'#ff6f7f');rect(5*u,-13*u,3*u,3*u,'#ff6f7f');ctx.restore()}
function drawEnemyHp(e){if(e.type!=='boss')return;var p=project(e.x,e.z),w=100*p.s;outlineRect(p.x-w/2,p.y-82*p.s,w,8*p.s,'#52354d','#35243c',2);rect(p.x-w/2+2,p.y-82*p.s+2,(w-4)*(e.hp/e.maxHp),Math.max(2,8*p.s-4),'#8be28d');pixelText(String(Math.max(0,Math.ceil(e.hp))),p.x,p.y-62*p.s,Math.max(12,Math.round(22*p.s)),'#fff8dc')}
function drawBullet(b){var p=project(b.x,b.z);if(!p.depth)return;var s=Math.max(2,Math.round(6*p.s));rect(p.x-s/2,p.y-s/2,s,s,'#35243c');rect(p.x-s/2+1,p.y-s/2+1,Math.max(1,s-2),Math.max(1,s-2),'#b24f4d')}
function drawChest(c){var p=project(c.x,c.z);if(!p.depth)return;var u=Math.max(1,Math.round(4*p.s));ctx.save();ctx.translate(ir(p.x),ir(p.y));rect(-8*u,-6*u,16*u,12*u,'#35243c');rect(-7*u,-5*u,14*u,10*u,'#c57b3a');rect(-7*u,-2*u,14*u,2*u,'#ffd56a');rect(-1*u,-3*u,2*u,5*u,'#fff0a8');ctx.restore();pixelText(String(Math.max(0,Math.ceil(c.hp))),p.x,p.y-34*p.s,Math.max(10,Math.round(17*p.s)),'#fff8dc')}
function drawGate(g){var p=project(0,g.z);if(!p.depth)return;var total=p.roadHalf*1.75,gap=4*p.s,h=105*p.s,y=p.y-h,half=total/2-gap;drawGateSide(W/2-total/2,y,half,h,g.left,p.s);drawGateSide(W/2+gap,y,half,h,g.right,p.s)}
function drawGateSide(x,y,w,h,o,s){var frame=o[3];outlineRect(x,y,w,h,'#fff8dc','#35243c',Math.max(2,Math.round(3*s)));rect(x,y,Math.max(4,8*s),h,frame);rect(x+w-Math.max(4,8*s),y,Math.max(4,8*s),h,frame);rect(x,y,w,Math.max(4,8*s),frame);pixelText(o[0],x+w/2,y+h*.58,Math.max(8,Math.round(15*s)),frame)}
function drawParticles(){for(var i=0;i<particles.length;i++){var p=particles[i];ctx.globalAlpha=clamp(p.life*2,0,1);rect(p.x,p.y,p.size,p.size,p.color)}ctx.globalAlpha=1}
function drawTexts(){for(var i=0;i<floatTexts.length;i++){var t=floatTexts[i];ctx.globalAlpha=clamp(t.life*1.6,0,1);pixelText(t.text,t.x,t.y,t.size,t.color)}ctx.globalAlpha=1}
function draw(){ctx.save();if(screenShake>.3)ctx.translate(ir((Math.random()-.5)*screenShake),ir((Math.random()-.5)*screenShake));drawSky();drawRoad();drawPetals();var all=[];gates.forEach(function(v){all.push({z:v.z,type:'gate',v:v})});enemies.forEach(function(v){all.push({z:v.z,type:'enemy',v:v})});chests.forEach(function(v){all.push({z:v.z,type:'chest',v:v})});bullets.forEach(function(v){all.push({z:v.z,type:'bullet',v:v})});all.sort(function(a,b){return b.z-a.z});for(var i=0;i<all.length;i++){if(all[i].type==='gate')drawGate(all[i].v);else if(all[i].type==='enemy'){drawEnemy(all[i].v);drawEnemyHp(all[i].v)}else if(all[i].type==='chest')drawChest(all[i].v);else drawBullet(all[i].v)}var pp=project(player.x,0);if(!(player.invincible>0&&Math.floor(player.invincible*14)%2===0))drawDaifuku(pp.x,525,1);if(player.shield>0){ctx.strokeStyle='#c39bff';ctx.lineWidth=4;ctx.strokeRect(ir(pp.x-38),475,76,74)}drawParticles();drawTexts();if(combo>=3)pixelText('COMBO x'+combo,W/2,115,18,'#ffd56a');if(player.magnet>0)pixelText('豆磁力 '+Math.ceil(player.magnet),W/2,137,13,'#70c9ef');if(waveBanner>0){ctx.globalAlpha=clamp(waveBanner,0,1);outlineRect(80,250,200,64,'#fff8dc','#35243c',5);pixelText('第 '+wave+' 波',180,282,28,'#ff87a0');ctx.globalAlpha=1}if(bossBanner>0){ctx.globalAlpha=clamp(bossBanner,0,1);outlineRect(48,235,264,82,'#35243c','#fff8dc',5);pixelText('抹茶大王 登場!',180,276,24,'#ffd56a');ctx.globalAlpha=1}if(whiteFlash>0){ctx.globalAlpha=whiteFlash;rect(0,0,W,H,'#fff');ctx.globalAlpha=1}ctx.restore()}
function loop(now){if(!running)return;var dt=Math.min((now-lastTime)/1000,.034);lastTime=now;update(dt);draw();if(running)requestAnimationFrame(loop)}
function pointerToTarget(clientX){var r=canvas.getBoundingClientRect(),nx=(clientX-r.left)/r.width;player.targetX=clamp((nx-.5)*2,-.88,.88)}
canvas.addEventListener('pointerdown',function(e){dragging=true;if(canvas.setPointerCapture)canvas.setPointerCapture(e.pointerId);pointerToTarget(e.clientX)});canvas.addEventListener('pointermove',function(e){if(dragging)pointerToTarget(e.clientX)});canvas.addEventListener('pointerup',function(){dragging=false});canvas.addEventListener('pointercancel',function(){dragging=false});window.addEventListener('keydown',function(e){if(e.code==='ArrowLeft'||e.code==='KeyA')player.targetX-=.18;if(e.code==='ArrowRight'||e.code==='KeyD')player.targetX+=.18;player.targetX=clamp(player.targetX,-.88,.88)});
id('startBtn').addEventListener('click',startGame);id('restartBtn').addEventListener('click',startGame);id('muteBtn').addEventListener('click',function(){muted=!muted;id('muteBtn').textContent=muted?'×':'♪'});resetWorldDecor();updateHud();draw();
})();