window.PG=(()=>{
  const G={};
  G.canvas=document.getElementById('game');G.ctx=G.canvas.getContext('2d');G.W=G.canvas.width;G.H=G.canvas.height;
  G.ui={score:document.getElementById('score'),balls:document.getElementById('balls'),combo:document.getElementById('combo'),high:document.getElementById('high'),marquee:document.getElementById('marquee'),powerSlider:document.getElementById('powerSlider'),powerValue:document.getElementById('powerValue'),launch:document.getElementById('launchBtn'),auto:document.getElementById('autoBtn'),reset:document.getElementById('resetBtn'),wrap:document.querySelector('.game-wrap'),bonus:document.querySelector('.bonus-slot'),slotReels:[...document.querySelectorAll('.mini-reel')],slotSpin:document.getElementById('slotSpinBtn'),slotStatus:document.getElementById('slotStatus'),slotEnergy:document.getElementById('slotEnergy'),slotFill:document.getElementById('slotMeterFill'),effect:document.getElementById('effectBadge')};
  G.p={bg:'#091333',rail:'#3b2e78',white:'#fff6d6',pink:'#ff4f9a',cyan:'#4ee9ff',yellow:'#ffd84d',green:'#56e39f',red:'#ff5a5f',shadow:'#080615'};
  G.s={score:0,balls:50,combo:1,high:loadHigh(),power:.55,auto:false,lastAuto:0,shake:0,particles:[],ballsLive:[],texts:[],pointer:false,pointerY:0,moved:false,hud:true,slotEnergy:0,slotSpinning:false,slotTimer:null,feverUntil:0,shield:0,superShots:0,lastEffect:-1};
  G.pins=[];G.bumpers=[];G.slots=[];G.gravity=.18;G.friction=.995;G.bounce=.72;G.SLOT_MAX=6;G.symbols=['♥','◆','★','⚡','♛','7'];G.compact=matchMedia?.('(max-width:600px)').matches??false;G.reduced=matchMedia?.('(prefers-reduced-motion:reduce)').matches??false;
  function loadHigh(){try{return Number(localStorage.getItem('pixelPachinkoHigh')||0)}catch{return 0}}
  G.saveHigh=()=>{try{localStorage.setItem('pixelPachinkoHigh',String(G.s.high))}catch{}};
  G.haptic=(v=8)=>{'vibrate'in navigator&&navigator.vibrate(v)};
  G.rand=()=>{if(crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}return Math.random()};
  G.randomSymbol=(except='')=>{let x=G.symbols[Math.floor(G.rand()*G.symbols.length)],n=0;while(x===except&&n++<6)x=G.symbols[Math.floor(G.rand()*G.symbols.length)];return x};
  G.isFever=()=>performance.now()<G.s.feverUntil;
  G.buildBoard=()=>{G.pins.length=G.bumpers.length=G.slots.length=0;for(let row=0;row<11;row++){const y=170+row*55,off=row%2?104:72;for(let x=off;x<615;x+=66){if(x>535&&row<3)continue;G.pins.push({x,y,r:7,flash:0})}}G.bumpers.push({x:230,y:300,r:30,color:G.p.cyan,label:'20',value:20,flash:0},{x:410,y:350,r:34,color:G.p.pink,label:'50',value:50,flash:0},{x:300,y:500,r:28,color:G.p.yellow,label:'30',value:30,flash:0},{x:500,y:560,r:30,color:G.p.green,label:'40',value:40,flash:0},{x:165,y:615,r:26,color:G.p.red,label:'25',value:25,flash:0});const vals=[50,100,250,1000,250,100,50],cols=[G.p.cyan,G.p.green,G.p.yellow,G.p.pink,G.p.yellow,G.p.green,G.p.cyan];for(let i=0;i<7;i++)G.slots.push({x:46+i*84,y:830,w:84,h:74,value:vals[i],color:cols[i],label:i===3?'JACKPOT':String(vals[i])})};
  G.setHigh=(persist=true)=>{if(G.s.score>G.s.high){G.s.high=G.s.score;if(persist)G.saveHigh()}};
  G.effectLabel=()=>{const left=Math.max(0,Math.ceil((G.s.feverUntil-performance.now())/1000));return left?`FEVER ${left}s`:G.s.shield?`CROWN ${G.s.shield}`:G.s.superShots?`SUPER ${G.s.superShots}`:'NORMAL'};
  G.updateHud=()=>{const s=G.s,u=G.ui,pct=Math.round(s.power*100),effect=G.effectLabel();u.score.textContent=String(s.score).padStart(6,'0');u.balls.textContent=s.balls;u.combo.textContent='x'+s.combo;u.high.textContent=String(s.high).padStart(6,'0');u.powerSlider.value=String(pct);u.powerValue.textContent=`${pct}%`;u.launch.disabled=s.balls<=0&&s.superShots<=0;u.slotEnergy.textContent=s.slotEnergy;u.slotFill.style.width=`${s.slotEnergy/G.SLOT_MAX*100}%`;u.slotSpin.disabled=s.slotSpinning||s.slotEnergy<G.SLOT_MAX;u.bonus.classList.toggle('ready',!s.slotSpinning&&s.slotEnergy>=G.SLOT_MAX);u.effect.textContent=effect;u.effect.classList.toggle('active',effect!=='NORMAL');u.wrap.classList.toggle('fever',G.isFever());s.hud=false};
  G.particles=(x,y,color,count=10)=>{for(let i=0;i<count;i++)G.s.particles.push({x,y,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5,life:(G.compact?16:20)+Math.random()*(G.compact?14:20),color,size:2+Math.floor(Math.random()*4)})};
  G.float=(x,y,text,color=G.p.yellow)=>G.s.texts.push({x,y,text,color,life:60});
  G.directScore=(points,text,color=G.p.yellow)=>{G.s.score+=points;G.setHigh();G.float(G.W/2,145,text||`+${points}`,color);G.updateHud()};
  G.energy=(amount,source='')=>{if(amount<=0)return;const was=G.s.slotEnergy>=G.SLOT_MAX;G.s.slotEnergy=Math.min(G.SLOT_MAX,G.s.slotEnergy+amount);if(!was&&G.s.slotEnergy>=G.SLOT_MAX){G.ui.slotStatus.textContent='能量已滿！老虎機準備完成';G.haptic([12,30,25]);clearTimeout(G.s.slotTimer);G.s.slotTimer=setTimeout(()=>{if(G.s.slotEnergy>=G.SLOT_MAX&&!G.s.slotSpinning)G.spinSlot()},800)}else if(source&&!G.s.slotSpinning)G.ui.slotStatus.textContent=`${source}：SLOT +${amount}`;G.updateHud()};
  G.award=(points,x,y,color=G.p.yellow)=>{const gained=points*G.s.combo*(G.isFever()?3:1);G.s.score+=gained;G.setHigh();G.float(x,y,`+${gained}`,color);G.updateHud()};
  G.collide=(ball,obj,extra=0)=>{const dx=ball.x-obj.x,dy=ball.y-obj.y,d=Math.hypot(dx,dy),min=ball.r+obj.r+extra;if(d<min&&d>0){const nx=dx/d,ny=dy/d,over=min-d;ball.x+=nx*over;ball.y+=ny*over;const dot=ball.vx*nx+ball.vy*ny;ball.vx-=(1+G.bounce)*dot*nx;ball.vy-=(1+G.bounce)*dot*ny;ball.vx+=(Math.random()-.5)*.35;return true}return false};
  G.launch=()=>{const s=G.s,superBall=s.superShots>0;if(s.balls<=0&&!superBall){G.ui.marquee.textContent=s.ballsLive.length?'等待最後的彈珠落下！':'彈珠用完了，按重新開始！';return}if(superBall)s.superShots--;else s.balls--;s.ballsLive.push({x:655,y:790,vx:superBall?-1.25-Math.random()*.4:-.6-Math.random()*.25,vy:superBall?-17.5-s.power*8:-11.5-s.power*9,r:superBall?11:9,alive:true,trail:[],super:superBall});G.particles(655,790,superBall?G.p.pink:G.p.cyan,superBall?14:(G.compact?5:8));G.haptic(superBall?[12,20,22]:6);G.ui.marquee.textContent=superBall?`⚡ 超級彈珠！剩餘 ${s.superShots} 發`:['發射！','好球！','命運啟動！','衝向 JACKPOT！'][Math.floor(Math.random()*4)];G.updateHud()};
  G.finish=(ball)=>{if(!ball.alive)return;ball.alive=false;const s=G.s,slot=G.slots.find(x=>ball.x>=x.x&&ball.x<x.x+x.w&&ball.y>x.y-5);if(slot){G.award(slot.value,ball.x,slot.y-10,slot.color);s.combo=Math.min(s.combo+1,9);G.energy(2,'進入得分槽');s.shake=slot.value>=1000?18:6;G.particles(ball.x,slot.y,slot.color,slot.value>=1000?(G.compact?28:50):(G.compact?12:18));if(slot.value>=1000){s.balls+=10;G.ui.marquee.textContent='★ JACKPOT！獎勵 10 顆彈珠！★'}else G.ui.marquee.textContent=`得分槽 ${slot.value}！COMBO x${s.combo}`}else if(s.shield>0)G.ui.marquee.textContent=`♛ 皇冠保護：COMBO x${s.combo} 保留`;else{s.combo=1;G.ui.marquee.textContent='差一點！COMBO 重置'}if(s.shield>0)s.shield--;G.setHigh();G.updateHud()};
  G.reset=()=>{const s=G.s;s.score=0;s.balls=50;s.combo=1;s.ballsLive=[];s.particles=[];s.texts=[];s.auto=false;s.slotEnergy=0;s.slotSpinning=false;s.feverUntil=0;s.shield=0;s.superShots=0;clearTimeout(s.slotTimer);G.ui.auto.innerHTML='<span class="button-icon">∞</span>自動：關';G.ui.auto.classList.remove('auto-on');G.ui.auto.setAttribute('aria-pressed','false');G.ui.slotStatus.textContent='撞擊彩色轉盤累積能量';G.ui.marquee.textContent='新的挑戰開始！';G.ui.slotReels.forEach((r,i)=>G.setSlotReel(r,['7','★','◆'][i]));G.haptic(15);G.updateHud()};
  return G;
})();
